set foreign_key_checks = 0;

ALTER TABLE nxenesit MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE prinderit MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE komunat MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE shtetet MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE profesoret MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE lendet MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE profesoret_lendet MODIFY COLUMN id INT AUTO_INCREMENT;
ALTER TABLE notat MODIFY COLUMN id INT AUTO_INCREMENT;

set foreign_key_checks = 1;